spring.application.name=demo

# H2 config
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none

# show SQL (debug)
spring.jpa.show-sql=true

# enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# flyway
spring.flyway.locations=classpath:db/migrations,classpath:db/data
spring.flyway.clean-disabled=false

# srping security
server.servlet.session.timeout=60d

# Thymeleaf
spring.web.resources.static-locations=classpath:/static/